live_config_reload = true

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "SF Mono"
style = "Italic"

[font.normal]
family = "SF Mono"
style = "Regular"

[font.offset]
x = 0
y = 3

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[window]
decorations = "buttonless"
dynamic_padding = true
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 0
