" Generated by vim-plug
" Tue Feb 20 18:36:08 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['argtextobj.vim'].commit = 'f3fbe427f7b4ec436416a5816d714dc917dc530b'
silent! let g:plugs['blamer.nvim'].commit = 'e0d43c11697300eb68f00d69df8b87deb0bf52dc'
silent! let g:plugs['coc-fzf'].commit = '96490e570daf1c10679ac0b183ebf2ca1024b079'
silent! let g:plugs['coc.nvim'].commit = '7b9e1ef0a1399907c51d23b6080b94a5aba4a654'
silent! let g:plugs['copilot.vim'].commit = '79e1a892ca9b4fa6234fd25f2930dba5201700bd'
silent! let g:plugs['fzf'].commit = 'ca747a2b5465961b23aa09606412877dd482a874'
silent! let g:plugs['fzf.vim'].commit = '5ab282c2f4a597fa655f39f36e7ee8e97bf51650'
silent! let g:plugs['gruvbox'].commit = 'f1ecde848f0cdba877acb0c740320568252cc482'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['nvim-treesitter'].commit = 'e04ce8bcec4dec3551d7ec4fa6d737d183433bfd'
silent! let g:plugs['split-term.vim'].commit = 'a4e28cab77ad07fc8a0ebb62a982768c02eb287c'
silent! let g:plugs['taboo.vim'].commit = 'caf948187694d3f1374913d36f947b3f9fa1c22f'
silent! let g:plugs['term-edit.nvim'].commit = 'e04f69d5828c6e6a4d81c34f75f18762fad50372'
silent! let g:plugs['undoquit.vim'].commit = '96935cae0c04ab9c7384afe1d2537ce883672e8c'
silent! let g:plugs['vim-ai'].commit = 'ed6333e968d563c12b24cbd78605578914a7f32a'
silent! let g:plugs['vim-checkbox'].commit = '1000afeda19c989c13ebdc2640c4d49f77cd0143'
silent! let g:plugs['vim-commentary'].commit = 'f67e3e67ea516755005e6cccb178bc8439c6d402'
silent! let g:plugs['vim-expand-region'].commit = '966513543de0ddc2d673b5528a056269e7917276'
silent! let g:plugs['vim-fugitive'].commit = '011cf4fcb93a9649ffc6dcdff56ef948f5d0f7cc'
silent! let g:plugs['vim-gh-line'].commit = '731751fdfa4f64a061dbc7088cb7b2f12e0828ad'
silent! let g:plugs['vim-gitgutter'].commit = '67ef116100b40f9ca128196504a2e0bc0a2753b0'
silent! let g:plugs['vim-jsx-pretty'].commit = '6989f1663cc03d7da72b5ef1c03f87e6ddb70b41'
silent! let g:plugs['vim-obsession'].commit = 'fe9d3e1a9a50171e7d316a52e1e56d868e4c1fe5'
silent! let g:plugs['vim-prosession'].commit = 'a79ac2677c5f7ee766454b6c30f21bc033049037'
silent! let g:plugs['vim-visual-multi'].commit = 'cff14071098de5279743b009c496303995fe4df9'
silent! let g:plugs['vindent.vim'].commit = '3f81a2db9303ba3bd858d64a4dda719fadc14615'
silent! let g:plugs['wilder.nvim'].commit = '679f348dc90d80ff9ba0e7c470c40a4d038dcecf'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['winshift.nvim'].commit = '37468ed6f385dfb50402368669766504c0e15583'

PlugUpdate!

