#!/usr/bin/env sh

YABAI_CERT=yabai-cert sh -c "$(curl -sSL "https://git.io/update-yabai")" &

# general space settings
yabai -m config layout bsp
yabai -m config top_padding    0
yabai -m config bottom_padding 0
yabai -m config left_padding   0
yabai -m config right_padding  0
yabai -m config window_gap     5

# global settings
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5
yabai -m config window_placement second_child
yabai -m config window_border off
yabai -m config auto_balance on
yabai -m config mouse_follows_focus on

echo "yabai configuration loaded.."
