#!/usr/bin/env sh

# general space settings
yabai -m config layout bsp
yabai -m config window_gap 5

# global settings
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5
yabai -m config split_ratio 0.50
yabai -m config window_placement second_child
yabai -m config window_border off

echo "yabai configuration loaded.."
