version: "3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./dashboard:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    environment:
      - TZ=America/New_York
      - PGID=1001
      - PUID=1001
    ports:
      - 8096:8096
      - 1900:1900
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./media:/media
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr/config:/app/config
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./jackett/config:/config
      - ./media:/media:z
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./sonarr/config:/config
      - ./qbittorrent/torrents:/torrents:z
      - ./media/tv:/media:z
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./radarr/config:/config
      - ./qbittorrent/torrents:/torrents:z
      - ./media/movies:/media:z
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - ./bazarr/config:/config
      - ./media/bazarr:/media:z
    ports:
      - 6767:6767
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./qbittorrent/config:/config:z
      - ./qbittorrent/torrents:/torrents:z
      - ./media:/media:z
    restart: unless-stopped
