version: 2.1

services: 
  jellyfin:
    container_name: jellyfin 
    image: jellyfin/jellyfin 
    user: 1000:1000 
    environment: 
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin 
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin 
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin 
      - JELLYFIN_LOG_DIR=/var/log/jellyfin 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/jellyfin/etc:/etc/jellyfin 
      - ./configs/jellyfin/var-cache:/var/cache/jellyfin 
      - ./configs/jellyfin/var-lib:/var/lib/jellyfin 
      - ./configs/jellyfin/var-log:/var/log/jellyfin 
      - ./configs/jellyfin/timezone:/etc/timezone 
      - myMedia:/mnt/media 
    group_add: 
      - "109" 
    network_mode: "host" 
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128 
    restart: unless-stopped 
  firefox: 
    image: lscr.io/linuxserver/firefox:latest 
    container_name: firefox 
    security_opt: 
      - seccomp:unconfined 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=Africa/Casablanca 
      - DRINODE=/dev/dri/renderD128 
      - DISABLE_IPV6=true 
      - DOCKER_MODS=linuxserver/mods:firefox-fonts 
    volumes: 
      - ./configs/firefox:/config 
    ports: 
      - 3001:3001 
    networks: 
      - firefox 
    shm_size: "1gb" 
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128 
    group_add: 
      - "109" 
    restart: unless-stopped 
  duplicati: 
    image: lscr.io/linuxserver/duplicati:latest 
    container_name: duplicati 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/duplicati/config:/config 
      - ./configs:/source 
      - ./docker-compose.yml:/source/docker-compose.yml 
      - ./configs/duplicati/restore:/restore 
    networks: 
      - duplicati 
    ports: 
      - 8200:8200 
    restart: unless-stopped 
  bazarr: 
    image: lscr.io/linuxserver/bazarr:latest 
    container_name: bazarr 
    hostname: bazarr 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/mediarr/bazarr:/config 
      - myMedia:/mnt/media 
    ports: 
      - 6767:6767 
    restart: unless-stopped 
    depends_on: 
      - sonarr 
      - radarr 
  jellyseerr: 
    image: fallenbagel/jellyseerr:latest 
    container_name: jellyseerr 
    hostname: jellyseerr 
    networks: 
      - mediarr 
    user: 1000:1000 
    environment: 
      - TZ=Africa/Casablanca 
    ports: 
      - 5055:5055 
    volumes: 
      - ./configs/mediarr/jellyseerr:/app/config 
    restart: unless-stopped 
    depends_on: 
      - sonarr 
      - radarr 
  prowlarr: 
    image: linuxserver/prowlarr:latest 
    container_name: prowlarr 
    hostname: prowlarr 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=1000 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/mediarr/prowlarr:/config 
    ports: 
      - 9696:9696 
    restart: unless-stopped 
    depends_on: 
      - flaresolverr 
  flaresolverr: 
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr 
    hostname: flaresolverr 
    networks: 
      - mediarr 
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
      - TZ=Africa/Casablanca 
    restart: unless-stopped 
  qbittorrent: 
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent 
    hostname: qbittorrent 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=100 
      - TZ=Africa/Casablanca 
      - WEBUI_PORT=8080 
    volumes: 
      - ./configs/mediarr/qbittorrent:/config 
      - myDlFolders:/downloads 
    ports: 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp 
    restart: unless-stopped 
  radarr: 
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    hostname: radarr 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=100 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/mediarr/radarr:/config 
      - myMedia:/mnt/media 
      - myDlFolders:/mnt/downloads 
    ports: 
      - 7878:7878 
    restart: unless-stopped 
    depends_on: 
      - prowlarr 
      - qbittorrent 
      - jellyfin 
  readarr: 
    image: lscr.io/linuxserver/readarr:develop 
    container_name: readarr 
    hostname: readarr 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=100 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./mediarr/readarr:/config 
      - myMedia:/mnt/media 
      - myDlFolders:/mnt/downloads 
    ports: 
      - 8787:8787 
    restart: unless-stopped 
    depends_on: 
      - prowlarr 
      - qbittorrent 
  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    hostname: sonarr 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=100 
      - TZ=Africa/Casablanca 
    volumes: 
      - ./configs/mediarr/sonarr:/config 
      - myMedia:/mnt/media 
      - myDlFolders:/mnt/downloads 
    depends_on: 
      - prowlarr 
      - qbittorrent 
      - jellyfin 
    ports: 
      - 8989:8989 
    restart: unless-stopped 
networks: 
  firefox: 
    driver: bridge 
  duplicati: 
    driver: bridge 
  mediarr: 
    driver: bridge
volumes:
  myMedia:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/media
  myDlFolders:
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /mnt/HDD/downloads
